### ISSUE TITLE
Request : Red Teaming Around Your Backyard

### ISSUE THREAD

**Issue by ShadowDrifterII** [ORCA666/Hacking-P-B#2]
Red Teaming Around Your Backyard While Drinking Our Juice in The Hood: Cyber Secrets: 3
https://www.amazon.com/gp/product/B089RQ5QMN?ref_=dbs_m_mng_rwt_calw_tkin_2&storeType=ebooks

**Comment by ORCA666** [comment]
hey, well at least try something like hey, hi, if u please, can u, thanks, thanks for ur time ...
i tried getting it, i coudnt find it, idk where u got this book lol, but ill inform u if i found it np.

**Comment by ShadowDrifterII** [comment]
I'm sorry and thanks for your respond.

I overlooked your happiness in an attempt to make myself happy, only to realize that my happiness lies in yours. I am sorry, please forgive me :)
Unknown

**Comment by ORCA666** [comment]
@ShadowDrifterII lol bro i was just joking :)
